const nudges = [
    ['Blue', 'Yellow', 'Purple'],
    ['Pink', 'Green', 'Yellow'],
    ['Purple', 'Yellow'],
    ['Orange', 'Purple'],
    ['Orange', 'Yellow'],
    ['Blue', 'Red'],
    ['Green', 'Pink', 'Purple'],
    ['Red', 'Purple', 'Blue'],
    ['Yellow', 'Pink'],
    ['Green', 'Blue', 'Yellow'],
    ['Purple', 'Yellow', 'Orange'],

    ['Pink', 'Orange', 'Green'],
    ['Blue', 'Yellow', 'Pink'],
    ['Pink', 'Orange'],
    ['Red', 'Green'],
    ['Blue', 'Red', 'Orange'],
    ['Blue', 'Pink', 'Green'],
    ['Red', 'Purple'],
    ['Red', 'Blue', 'Green'],
    ['Blue', 'Orange', 'Green'],
    ['Green', 'Orange', 'Yellow'],

    ['Yellow', 'Orange'],
    ['Purple', 'Yellow', 'Pink'],
    ['Orange', 'Purple'],
    ['Yellow', 'Purple', 'Orange'],
    ['Red', 'Orange', 'Purple'],
    ['Orange', 'Purple'],
    ['Purple', 'Yellow'],
    ['Green', 'Purple'],
    ['Purple'],
    ['Red', 'Green', 'Orange'],

    ['Orange', 'Red', 'Purple'],
    ['Green', 'Purple', 'Pink'],
    ['Yellow', 'Orange'],
    ['Pink', 'Green'],
    ['Green', 'Purple', 'Orange'],
    ['Blue', 'Orange', 'Purple'],
    ['Red', 'Pink', 'Yellow'],
    ['Green', 'Pink'],
    ['Blue', 'Red'],
    ['Purple', 'Yellow'],

    ['Red', 'Orange', 'Blue'],
    ['Purple', 'Red', 'Pink'],
    ['Orange', 'Yellow', 'Pink'],
    ['Red', 'Blue'],
    ['Blue', 'Red', 'Pink'],
    ['Orange', 'Purple', 'Red', 'Green', 'Blue']
]

module.exports =  { nudges };